##### libraries #####
library(httr)
library(jsonlite)
library(dplyr)
library(stringr)
library(ggplot2)
library(ggthemes)
library(scales)
library(tidyr)

setwd("wordle-data-analysis/")

##### download game script #####
url = "https://www.powerlanguage.co.uk/wordle/main.e65ce0a5.js"
wordle_script_text = GET(url) %>%
  content(as = "text", encoding = "UTF-8")

##### parse word list #####

# I couldn't figure out how to extract this programmatically
# so instead I'm extracting from the beginning of the first word
# through the end of the last word
word_list = substr(
  wordle_script_text,
  # cigar is the first word
  str_locate(wordle_script_text, "cigar")[,"start"],
  # shave is the last word
  str_locate(wordle_script_text, "shave")[,"end"]) %>%
  # remove slashes
  str_remove_all("\"") %>%
  # split using commas
  str_split(",") %>%
  # convert to DF
  data.frame() %>%
  # rename column
  select(word = 1) %>%
  mutate(word = toupper(word))

##### determine letter frequency #####

letter_list = word_list %>%
  as.character() %>%
  str_split("") %>%
  data.frame() %>%
  # need to remove the "c" that was added in the string split
  filter(row_number() != 1) %>%
  select(letter = 1) %>%
  filter(letter %in% LETTERS) %>%
  group_by(letter) %>%
  summarize(freq = n()) %>%
  arrange(desc(freq))

##### plot overall letter frequency #####

ggplot(letter_list, aes(x = reorder(letter, (-freq)), y = freq)) +
  geom_bar(fill = "lightblue",
           stat = "identity") +
  geom_text(aes(x = reorder(letter, (-freq)),
                y = freq,
                label = comma(freq, accuracy = 1),
                vjust = 1),
            size = 3) +
  scale_y_continuous(labels = comma,
                     expand = c(0,0)) +
  theme_clean() +
  xlab("Letter") +
  ylab("Frequency") +
  labs(caption = "Generated by Arthur Holtz\nlinkedin.com/in/arthur-holtz/") +
  ggtitle("Letter Frequency in Wordle's Official Word List")

ggsave(filename = "Letter Frequency in Wordle.png")

##### frequency by letter position #####

ordered_letter_list = word_list %>%
  separate(word,
           sep = "",
           # for some reason, R puts a blank column in the beginning
           # so I add a 6th column and then remove the first
           into = as.character(1:6)) %>%
  select(-1,
         "l_1" = 2,
         "l_2" = 3,
         "l_3" = 4,
         "l_4" = 5,
         "l_5" = 6)

# need a function to build the summary for each letter position
build_df = function(df, col_name) {
  new_df = df %>%
    group_by(letter = eval(sym(col_name))) %>%
    summarize(freq = n()) %>%
    arrange(desc(freq))

  return(new_df)
}

##### plot frequency by position #####

for (i in 1:5) {
  this_df = paste0("letter_", i)
  assign(this_df, build_df(ordered_letter_list, paste0("l_", i)))

  title = paste0("Letter # ", i, " Frequency in Wordle's Official Word List")

  ggplot(eval(sym(this_df)), aes(x = reorder(letter, (-freq)), y = freq)) +
    geom_bar(fill = "lightblue",
             stat = "identity") +
    geom_text(aes(x = reorder(letter, (-freq)),
                  y = freq,
                  label = comma(freq, accuracy = 1),
                  vjust = 1),
              size = 3) +
    scale_y_continuous(labels = comma,
                       expand = c(0,0)) +
    theme_clean() +
    xlab("Letter") +
    ylab("Frequency") +
    labs(caption = "Generated by Arthur Holtz\nlinkedin.com/in/arthur-holtz/") +
    ggtitle(title)

  fn = paste0("Letter # ", i, " Frequency.png")

  ggsave(fn)
}

