##### libraries #####
library(httr)
library(dplyr)
library(stringr)
library(ggplot2)
library(ggthemes)
library(scales)
library(purrr)
library(furrr)

setwd("~/wordle-data-analysis/")

score_one_word = function(guess, dict, pos_score = 3, let_score = 2) {
  dat = expand.grid(
    g_pos = 1:nchar(guess),
    d_word = dict) %>%
    mutate(
      g_word = guess,
      g_let = str_sub(guess, start = g_pos, end = g_pos),
      d_let = str_sub(d_word, g_pos, g_pos))

  dat %<>%
    mutate(
      raw_score = case_when(
        g_let == d_let ~ pos_score,
        str_detect(d_word, g_let) ~ let_score,
        T ~ 0)) %>%
    # by arranging this way we put the position matches first, which is key
    #  to making sure we give the full points for position matches.
    arrange(desc(raw_score))

  # Correct the scores so we don't over-award points for repeated guess letters.
  #  For instance "eerie" is probably not a good guess but it would get a very
  #  high score as is with three E's.
  dat %<>%
    group_by(d_let) %>%
    # maximum number of letter matches that will be awarded:
    mutate(max_char = n()) %>%
    ungroup(.) %>%
    # number of raw matches found:
    group_by(g_let) %>%
    mutate(sum_char = 1:n()) %>%
    ungroup(.) %>%
    mutate(
      score = case_when(
        sum_char > max_char ~ 0, # special case, imagine "eerie"
        T ~ raw_score))

  score_out = dat %>%
    group_by(guess = g_word, dict_word = d_word) %>%
    summarize(score = sum(score), .groups = "drop") %>%
    group_by(guess) %>%
    summarize(score = mean(score), .groups = "drop") %>%
    pull(score)

  return(score_out)
}

##### download game script #####
url = "https://www.nytimes.com/games-assets/v2/3550.a8dc98cc4aa2289b8f04.js"
wordle_script_text = GET(url) %>%
  content(as = "text", encoding = "UTF-8")

##### parse word list #####

# I couldn't figure out how to extract this programmatically
# so instead I'm extracting from the beginning of the first word
# through the end of the last word
target_word_df <- substr(
  wordle_script_text,
  # cigar is the first word
  str_locate(wordle_script_text, "cigar")[,"start"],
  # augur is the last word
  str_locate(wordle_script_text, "augur")[,"end"]) %>%
  str_remove_all("\"") %>%
  str_split(",") %>%
  unlist(.) %>%
  tibble(word = .)

valid_word_df = substr(
  wordle_script_text,
  str_locate(wordle_script_text, "aahed")[,"start"],
  str_locate(wordle_script_text, "zymic")[,"end"]) %>%
  str_remove_all("\"") %>%
  str_split(",") %>%
  unlist(.) %>%
  tibble(word = .) %>%
  bind_rows(target_word_df) %>%
  arrange(word) %>%
  unique()

plan(multisession, workers = 8)

score_df = valid_word_df %>%
  mutate(score = future_map_dbl(.x = word,
                                .f = score_one_word,
                                dict = target_word_df$word)) %>%
  arrange(desc(score))

readr::write_csv(score_df, "All Words Avg Scores.csv")

score_df_w_target_words = target_word_df %>%
  mutate(score = future_map_dbl(.x = word,
                                .f = score_one_word,
                                dict = target_word_df$word)) %>%
  arrange(desc(score))

readr::write_csv(score_df_w_target_words, "Winning Words Avg Scores.csv")

#####

score_df = readr::read_csv("data/All Words Avg Scores.csv")

score_df %>%
  head(20) %>%
  ggplot(aes(x = reorder(word, (-score)), y = score)) +
  geom_col(fill = "lightblue") +
  scale_x_discrete() +
  scale_y_continuous(labels = comma,
                     expand = c(0, 0)) +
  coord_cartesian(ylim = c(2.95, 3.2)) +
  xlab("Word") +
  ggtitle("Top 20 Scoring Words", "Using any valid Wordle words") +
  labs(caption = "Generated by Arthur Holtz\nlinkedin.com/in/arthur-holtz/") +
  theme_clean() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5))

score_df_w_target_words = readr::read_csv("data/Winning Words Avg Scores.csv")

score_df_w_target_words %>%
  head(20) %>%
  ggplot(aes(x = reorder(word, (-score)), y = score)) +
  geom_col(fill = "lightblue") +
  scale_x_discrete() +
  scale_y_continuous(labels = comma,
                     expand = c(0, 0)) +
  coord_cartesian(ylim = c(2.9, 3.15)) +
  xlab("Word") +
  ggtitle("Top 20 Scoring Words", "Using only winning Wordle words") +
  labs(caption = "Generated by Arthur Holtz\nlinkedin.com/in/arthur-holtz/") +
  theme_clean() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5))
